export default function mainData() {
  const bodyObj = {
    generalStyles: [
      'main-bg-color',
      'secondary-bg-color',
      'third-bg-color',
      'main-text-color',
      'secondary-text-color',
      'header-bg-color',
      'header-text-color',
      'main-btn-bg-color',
      'main-btn-text-color',
      'secondary-btn-bg-color',
      'secondary-btn-text-color',
      'main-font',
      'seccondary-font',
      'headerBGColor',
      'headerTextColor',
    ],
    companyInfo: [
      'companyName',
      'address',
      'city',
      'state',
      'zip',
      'phoneNumber',
      'email',
      'hours',
      'socialLinkOne',
      'socialLinkTwo',
      'socialLinkThree',
      'socialLinkUrlOne',
      'socialLinkUrlTwo',
      'socialLinkUrlThree',
    ],
    homePage: [
      'homeTitle',
      'homeH2',
      'homeH3',
      'homeImgUrl',
      'homeImgType',
      'homeText',
      'homeBtnText',
      'homeBtnFunction',
      'hasReviews',
      'reviews',
      'hasCategories',
      'categories',
      'hasContactForm',
    ],
    reviews: ['id', 'reviewTitle', 'reviewScore', 'reviewText', 'reviewerName', 'reviewDate'],
    categoryPages: ['id', 'catTitle', 'catImgUrl', 'catSubHeader', 'catText', 'articleAmount', 'articleArray'],
    categoryArticles: [
      'id',
      'articleTitle',
      'articleImgUrl',
      'articleImgUrlTwo',
      'articleImgUrlThree',
      'articleText',
      'articleImgTextTwo',
      'articleImgTextThree',
    ],
    contactForm: [
      'has phone',
      'dDTitle',
      'dDOptionOne',
      'dDOptionTwo',
      'dDOptionThree',
      'dDOptionFour',
      'dDOptionFive',
      'checkboxTitle',
      'checkboxOptionOne',
      'checkboxOptionTwo',
      'checkboxOptionThree',
      'checkboxOptionFour',
      'checkboxOptionFive',
    ],
    header: ['companyLogoUrl', 'hasSocialLinks', 'hasContactUs', 'hasAboutUs', 'styleType'],
    footer: ['hasSocialLinks', 'styleType'],
  };
}
